### ISSUE TITLE
Path dependancy

### ISSUE THREAD

**Issue by Chan9390** [anantshri/present_revealjs_workflow_automation#15]
`present` runs only if the markdown file is present in the working directory. If tried to supply the path, error occurs.

For example:
```
root@root> present Desktop/mark.md
Present : Reveal.js Workflow Automation
Created by: Anant Shrivastava
Un-identified argument
setup : setup reveal.js environment
setup slide_name.md
clean : clear out all files
Thanks for using present service
```
It would be better if it handles path of a markdown file and creates or clears in a pre-defined custom Temp folder.

**Comment by anantshri** [comment]
So far the idea is to have isolated containers for the presentations so custom temp will not work. and that's the reason path's are not taken care off. there is a hard coded check to look for file in current directory to counter any issues that may arise if tool used outside working directory. Closing this as a non issue.

However if you feel a real need to have this feature pull requests are welcome.
